apiVersion: v1
kind: ConfigMap
metadata:
  # Name the ConfigMap uniquely per Helm release
  name: {{ .Release.Name }}-device-plugin-config
  labels:
    app.kubernetes.io/component: amd-nic
    app.kubernetes.io/part-of: amd-nic
  {{- include "helm-charts-k8s.labels" . | nindent 4 }}
  # Use the namespace where the Helm chart is deployed
  namespace: {{ .Release.Namespace }}
data:
  # The config.json content for the SR-IOV device plugin
  config.json: |
    {
      "resourceList": [{
        "resourceName": "nic", 
        "resourcePrefix": "amd.com", 
        "enableExporterHealthCheck": true,
        "selectors": {
          "vendors": ["1dd8"], 
          "devices": ["1002"],
          "drivers": ["ionic"],
          "excludeTopology": true,
          "isRdma": true
        }
      },
      {
        "resourceName": "vnic",
        "resourcePrefix": "amd.com",
        "enableExporterHealthCheck": true,
        "selectors": {
          "vendors": ["1dd8"], 
          "devices": ["1003"],
          "drivers": ["ionic"],
          "excludeTopology": true,
          "isRdma": true
        }
      }]
    }
