apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "helm-charts-k8s.fullname" . }}-controller-manager
  labels:
    app.kubernetes.io/component: amd-nic
    app.kubernetes.io/part-of: amd-nic
  {{- include "helm-charts-k8s.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.controllerManager.serviceAccount.annotations | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: amd-network-operator-device-plugin
  labels:
    app.kubernetes.io/component: amd-nic
    app.kubernetes.io/part-of: amd-nic
  {{- include "helm-charts-k8s.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.devicePlugin.serviceAccount.annotations | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: amd-network-operator-kmm-module-loader
  labels:
    app.kubernetes.io/component: amd-nic
    app.kubernetes.io/part-of: amd-nic
  {{- include "helm-charts-k8s.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.kmmModuleLoader.serviceAccount.annotations | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: amd-network-operator-node-labeller
  labels:
    app.kubernetes.io/component: amd-nic
    app.kubernetes.io/part-of: amd-nic
  {{- include "helm-charts-k8s.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.nodeLabeller.serviceAccount.annotations | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: amd-network-operator-metrics-exporter
  labels:
    app.kubernetes.io/component: amd-nic
    app.kubernetes.io/part-of: amd-nic
  {{- include "helm-charts-k8s.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.metricsExporter.serviceAccount.annotations | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: amd-network-operator-metrics-exporter-rbac-proxy
  labels:
    app.kubernetes.io/component: amd-nic
    app.kubernetes.io/part-of: amd-nic
  {{- include "helm-charts-k8s.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.metricsExporter.serviceAccount.annotations | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: amd-network-operator-test-runner
  labels:
    app.kubernetes.io/component: amd-nic
    app.kubernetes.io/part-of: amd-nic
  {{- include "helm-charts-k8s.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.testRunner.serviceAccount.annotations | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: amd-network-operator-config-manager
  labels:
    app.kubernetes.io/component: amd-nic
    app.kubernetes.io/part-of: amd-nic
  {{- include "helm-charts-k8s.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.configManager.serviceAccount.annotations | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: amd-network-operator-utils-container
  labels:
    app.kubernetes.io/component: amd-nic
    app.kubernetes.io/part-of: amd-nic
  {{- include "helm-charts-k8s.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.utilsContainer.serviceAccount.annotations | nindent 4 }}
