images:
  # contoller
  - target: docker.io/rocm/network-operator:v1.2.0
    k8s_comp_prefix:
      - network-operator-charts-controller
  # operands
  # cni-plugins
  - target: docker.io/rocm/k8s-cni-plugins:v1.2.0
  #utils
  - target: docker.io/rocm/network-operator-utils:v1.2.0
