#!/bin/bash

NUM_NODES=2
GPUS_PER_NODE=8

HOST1_IP="${1:-10.5.0.34}"
HOST2_IP="${2:-10.5.0.52}"
MCA_IF=${3:-eth0}
COLLECTIVE=${4:-all_reduce_perf}

export OMPI_DIR=/root/ompi/install
export PERF_TEST_DIR=/root/rccl-tests/build

RCCL_ENV=""
RCCL_ENV="$RCCL_ENV -x NCCL_DEBUG=VERSION"
RCCL_ENV="$RCCL_ENV -x HSA_NO_SCRATCH_RECLAIM=1"
RCCL_ENV="$RCCL_ENV -x IONIC_LOCKFREE=all"
RCCL_ENV="$RCCL_ENV -x NCCL_GDRCOPY_ENABLE=0"
RCCL_ENV="$RCCL_ENV -x NCCL_GDR_FLUSH_DISABLE=1"
RCCL_ENV="$RCCL_ENV -x NCCL_GRAPH_DUMP_FILE=/tmp/graph_all.txt"
RCCL_ENV="$RCCL_ENV -x NCCL_IB_GID_INDEX=1"
RCCL_ENV="$RCCL_ENV -x NCCL_PXN_DISABLE=0"
RCCL_ENV="$RCCL_ENV -x NCCL_IB_QPS_PER_CONNECTION=1"
RCCL_ENV="$RCCL_ENV -x NCCL_IB_TC=96"
RCCL_ENV="$RCCL_ENV -x NCCL_IB_FIFO_TC=184"
RCCL_ENV="$RCCL_ENV -x NCCL_IGNORE_CPU_AFFINITY=1"
RCCL_ENV="$RCCL_ENV -x NCCL_IB_USE_INLINE=1"
RCCL_ENV="$RCCL_ENV -x NCCL_NET_OPTIONAL_RECV_COMPLETION=1"
RCCL_ENV="$RCCL_ENV -x NCCL_SOCKET_IFNAME=${MCA_IF}"
RCCL_ENV="$RCCL_ENV -x NCCL_TOPO_DUMP_FILE=/tmp/topo_all.txt"
RCCL_ENV="$RCCL_ENV -x RCCL_GDR_FLUSH_GPU_MEM_NO_RELAXED_ORDERING=0"
RCCL_ENV="$RCCL_ENV -x UCX_UNIFIED_MODE=y"

# -- rccl run start ---
mkdir -p /tmp/run_logs
NP=$(( NUM_NODES * GPUS_PER_NODE ))
echo "MPI NP = $NP"
${OMPI_DIR}/bin/mpirun --np $NP \
    -H "$HOST1_IP":${GPUS_PER_NODE},"$HOST2_IP":${GPUS_PER_NODE} \
    -x PATH -x LD_LIBRARY_PATH -x LD_PRELOAD \
    --allow-run-as-root --mca plm_rsh_agent "ssh" \
    --mca btl ^vader,openib -mca btl_tcp_if_include $MCA_IF \
    ${RCCL_ENV} \
    $PERF_TEST_DIR/${COLLECTIVE} -b 1k -e 4G -n 6  -w 20 -c 0 -f 2 -g 1  | tee /tmp/run_logs/${COLLECTIVE}_$(date +%Y%m%d%H%M).log
