apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "helm-charts-openshift.fullname" . }}-controller-manager
  labels:
    app.kubernetes.io/component: amd-nic
    app.kubernetes.io/part-of: amd-nic
  {{- include "helm-charts-openshift.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.controllerManager.serviceAccount.annotations | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: amd-network-operator-device-plugin
  labels:
    app.kubernetes.io/component: amd-nic
    app.kubernetes.io/part-of: amd-nic
  {{- include "helm-charts-openshift.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.devicePlugin.serviceAccount.annotations | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: amd-network-operator-kmm-module-loader
  labels:
    app.kubernetes.io/component: amd-nic
    app.kubernetes.io/part-of: amd-nic
  {{- include "helm-charts-openshift.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.kmmModuleLoader.serviceAccount.annotations | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  # the node labeller service account name should be fixed, not templated
  name: amd-network-operator-node-labeller
  labels:
    app.kubernetes.io/component: amd-nic
    app.kubernetes.io/part-of: amd-nic
  {{- include "helm-charts-openshift.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.nodeLabeller.serviceAccount.annotations | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: amd-network-operator-metrics-exporter
  labels:
    app.kubernetes.io/component: amd-nic
    app.kubernetes.io/part-of: amd-nic
  {{- include "helm-charts-openshift.labels" . | nindent 4 }}
  annotations:
  annotations:
    {{- toYaml .Values.metricsExporter.serviceAccount.annotations | nindent 4 }}
