/*
Copyright (c) Advanced Micro Devices, Inc. All rights reserved.

Licensed under the Apache License, Version 2.0 (the \"License\");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an \"AS IS\" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by MockGen. DO NOT EDIT.
// Source: cniplugins.go
//
// Generated by this command:
//
//	mockgen -source=cniplugins.go -destination=mock_cniplugins.go -package=secondarynetwork SecondaryNetwork
//
// Package secondarynetwork is a generated GoMock package.
package secondarynetwork

import (
	reflect "reflect"

	v1alpha1 "github.com/ROCm/network-operator/api/v1alpha1"
	gomock "go.uber.org/mock/gomock"
	v1 "k8s.io/api/apps/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// MockSecondaryNetworkAPI is a mock of SecondaryNetworkAPI interface.
type MockSecondaryNetworkAPI struct {
	ctrl     *gomock.Controller
	recorder *MockSecondaryNetworkAPIMockRecorder
}

// MockSecondaryNetworkAPIMockRecorder is the mock recorder for MockSecondaryNetworkAPI.
type MockSecondaryNetworkAPIMockRecorder struct {
	mock *MockSecondaryNetworkAPI
}

// NewMockSecondaryNetworkAPI creates a new mock instance.
func NewMockSecondaryNetworkAPI(ctrl *gomock.Controller) *MockSecondaryNetworkAPI {
	mock := &MockSecondaryNetworkAPI{ctrl: ctrl}
	mock.recorder = &MockSecondaryNetworkAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSecondaryNetworkAPI) EXPECT() *MockSecondaryNetworkAPIMockRecorder {
	return m.recorder
}

// SetCNIPluginsAsDesired mocks base method.
func (m *MockSecondaryNetworkAPI) SetCNIPluginsAsDesired(nwConfigName string, ds *v1.DaemonSet, cniPluginsSpec *v1alpha1.CniPluginsSpec, nodeSelector map[string]string) (*runtime.Scheme, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetCNIPluginsAsDesired", nwConfigName, ds, cniPluginsSpec, nodeSelector)
	ret0, _ := ret[0].(*runtime.Scheme)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetCNIPluginsAsDesired indicates an expected call of SetCNIPluginsAsDesired.
func (mr *MockSecondaryNetworkAPIMockRecorder) SetCNIPluginsAsDesired(nwConfigName, ds, cniPluginsSpec, nodeSelector any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetCNIPluginsAsDesired", reflect.TypeOf((*MockSecondaryNetworkAPI)(nil).SetCNIPluginsAsDesired), nwConfigName, ds, cniPluginsSpec, nodeSelector)
}
