# networkconfig.yaml
apiVersion: amd.com/v1alpha1
kind: NetworkConfig
metadata:
  name: network-operator
  namespace: kube-amd-network
spec:
  selector:
    feature.node.kubernetes.io/amd-nic: "true"

  metricsExporter:
    enable: true
    serviceType: ClusterIP
    image: "docker.io/rocm/device-metrics-exporter:latest"

    rbacConfig:
      enable: true
      secret:
        name: server-metrics-tls

    prometheus:
      serviceMonitor:
        enable: true
        interval: 60s
        honorLabels: true
        labels:
          "example": "prom-token"
        attachMetadata:
          node: true
        tlsConfig:
          ca:
            configMap:
              key: ca.crt
              name: prom-server-ca
          serverName: my-metrics-service
          insecureSkipVerify: false
        authorization:
          type: Bearer
          credentials:
            key: token
            name: prom-token
